apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  type: NodePort
  #xternalIPs: #To use only in Microk8s or Kubeadm env
  #- 10.0.2.4
  selector:
    app: nginx
  ports:
    - name: nginx-http-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
    - name: nginx-https-port
      protocol: TCP
      port: 443
      targetPort: 443