apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/natan-dias/webserver-example.git
    targetRevision: main
    path: kustomize-option/overlays/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
