apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        #image: natandias1/jenkins:v1.0
        #image: docker.io/jenkins:2.60.3
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "500Mi"
            cpu: "10m"
          requests:
            memory: "500Mi"
            cpu: "10m"
        volumeMounts:
          - name: nginx-home
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-home
        persistentVolumeClaim:
          claimName: nginx-claim
        #hostPath:
          #path: /mnt/jenkins/jenkins